package com.example.fit2081week2task2;

import android.os.Bundle;
import android.view.View;
import android.widget.EditText;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import java.util.ArrayList;

public class RecyclerActivity extends AppCompatActivity {
    EditText mMovieName;
    EditText mMovieYear;
    EditText mMovieCountry;
    EditText mMovieGenre;
    EditText mMovieCost;
    EditText mMovieKeywords;

    ArrayList<MovieDetails> dataSource;
    Week6TaskAdapter adapter;
    RecyclerView recyclerView;
    RecyclerView.LayoutManager layoutManager;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.recycler_layout);

        mMovieName = findViewById(R.id.MovieNameEditText);/*This line identifies the text for use by looking for the id given to it, in this case the ID is MovieNameEditText (Generated by the program when I first created it)*/
        mMovieYear = findViewById(R.id.YearEditText);
        mMovieCountry = findViewById(R.id.CountryReleasedEditText);
        mMovieGenre = findViewById(R.id.GenreTextEdit);
        mMovieCost = findViewById(R.id.MovieCostEdit);
        mMovieKeywords = findViewById(R.id.KeywordsTextEdit);

        recyclerView=findViewById(R.id.recycler_layout_id);
        layoutManager=new LinearLayoutManager(this);
        recyclerView.setLayoutManager(layoutManager);

        dataSource=new ArrayList<MovieDetails>();
        adapter=new Week6TaskAdapter(dataSource);
        recyclerView.setAdapter(adapter);
    }
    public void addItem(View view) {
        MovieDetails newDetails = new MovieDetails(mMovieName.getText().toString(),mMovieYear.getText().toString(),mMovieCountry.getText().toString(),mMovieCost.getText().toString(),mMovieGenre.getText().toString(),mMovieKeywords.getText().toString());
        dataSource.add(newDetails);
        adapter.notifyDataSetChanged();

    }

}
